source "https://supermarket.chef.io"

cookbook 'yum-epel', '~> 0.6.5'
cookbook 'squid', '~> 1.1.1'
cookbook 'openvpn', git: 'git@github.com:xhost-cookbooks/openvpn.git'
cookbook 'base', path: "./cookbooks/base"
